// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMaBylnPQ-0Dr_znSjs2IIOWmD60BtQnY',
    appId: '1:53239051223:web:8aebc7b46e7208546dd192',
    messagingSenderId: '53239051223',
    projectId: 'mobalworld',
    authDomain: 'mobalworld.firebaseapp.com',
    storageBucket: 'mobalworld.appspot.com',
    measurementId: 'G-6XD5DXVQ01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB8bN2fhugKeuTZRBNXp81x9FFIkGWqAs',
    appId: '1:53239051223:android:68118880d83594096dd192',
    messagingSenderId: '53239051223',
    projectId: 'mobalworld',
    storageBucket: 'mobalworld.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7X5jqv0OpU0d8q9VztCWXuWgf2XOt6Dg',
    appId: '1:53239051223:ios:7c4ac599730540756dd192',
    messagingSenderId: '53239051223',
    projectId: 'mobalworld',
    storageBucket: 'mobalworld.appspot.com',
    androidClientId: '53239051223-1d6fmgs9344st4ca8svdugl00uukjou7.apps.googleusercontent.com',
    iosClientId: '53239051223-p3mllqhgpnph3pg4ehbdqn4t9itl5lml.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7X5jqv0OpU0d8q9VztCWXuWgf2XOt6Dg',
    appId: '1:53239051223:ios:99a00a0498251fbd6dd192',
    messagingSenderId: '53239051223',
    projectId: 'mobalworld',
    storageBucket: 'mobalworld.appspot.com',
    androidClientId: '53239051223-1d6fmgs9344st4ca8svdugl00uukjou7.apps.googleusercontent.com',
    iosClientId: '53239051223-oag3n90kg4f26vq1qlo9kpkuir2ljppf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3.RunnerTests',
  );
}
